# File that stores all constants for gui

APP_TITLE = 'MPM'
APP_GEOMETRY = '720x520'

ACCENT_COLOR = '#1A5ACA'
BACKGROUND_WHITE_COLOR = 'White'
BACKGROUND_GREY_COLOR = '#ededed'
HOVER_HIGHLIGHT_COLOR = '#fafafa'

SMALL_TEXT_SIZE = 12
MAIN_TEXT_SIZE = 15
APP_FONT = 'Lexend'

FONT_PRESET_MAIN = (APP_FONT, MAIN_TEXT_SIZE)
FONT_PRESET_SMALL = (APP_FONT, SMALL_TEXT_SIZE)

BUTTON_WIDTH = 60
