APP_TITLE = 'MPM'

ACCENT_COLOR = 'Blue'
BACKGROUND_WHITE_COLOR = 'White'
BACKGROUND_GREY_COLOR = 'Light grey'
HOVER_HIGHLIGHT_COLOR = 'Light grey'

SMALL_TEXT_SIZE = 11
MAIN_TEXT_SIZE = 14
APP_FONT = 'Lexend'

FONT_PRESET_MAIN = (APP_FONT, MAIN_TEXT_SIZE)
FONT_PRESET_SMALL = (APP_FONT, SMALL_TEXT_SIZE)

BUTTON_WIDTH = 60